### ISSUE TITLE
Abandoned branches?

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/simple-blackjack-cli#5]
Looks like Rose was working on some branches that are now behind master. Are they still relevant?

@deniznida @roseweixel

**Comment by roseweixel** [comment]
@markedwardmurray I was working on the tutorial when I found some issues with the order of the tests so I changed them on master and made a pull request (ea9be1e). Since the tutorial branch needs to be merged with solution I was waiting to make a pull request until my updated spec order was merged with solution.
